### ISSUE TITLE
Incompatibility between usability plugin and Code Review plugin in Redmine 4.0.x

### ISSUE THREAD

**Issue by jwalkerbg** [haru/redmine_code_review#16]
Hello, 

There is some incompatibility between CodeReview 1.0.0 and a plugin "usability" (http://rmplus.pro/en/redmine/plugins/usability). Unfortunately, I do not know where the problem comes from and where is the solution.

    Environment:
      Redmine version                4.0.3.stable
      Ruby version                   2.5.1-p57 (2018-03-29) [i386-mingw32]
      Rails version                  5.2.2.1
      Environment                    production
      Database adapter               Mysql2
      Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
      Mailer delivery                smtp
    SCM:
      Subversion                     1.8.19
      Git                            2.16.1
      Filesystem                     
    Redmine plugins:
      a_common_libs                  2.5.4
      Redmine Code Review            4.0.0
      redmine_issue_tabs             1.3.3
      redmine_issue_templates        0.3.1
      redmine_theme_changer          0.4.0
      usability                      2.4.0

The problem arises when entering project's Settings tab. Here is the log:

    ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x09deebe0>:0x09ee8018>
    Did you mean?  project_settings_tabs_without_usability):
        1: <h2><%=l(:label_settings)%></h2>
        2:
        3: <%= render_tabs project_settings_tabs %>
        4:
        5: <% html_title(l(:label_settings)) -%>
    
    plugins/redmine_code_review/lib/code_review_projects_helper_patch.rb:22:in `project_settings_tabs'
    plugins/usability/lib/usability/projects_helper_patch.rb:24:in `project_settings_tabs_with_usability'
    plugins/redmine_code_review/lib/code_review_projects_helper_patch.rb:22:in `project_settings_tabs'
    plugins/redmine_issue_templates/lib/issue_templates/projects_helper_patch.rb:6:in `project_settings_tabs'
    app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___309236401_83313420'
    lib/redmine/sudo_mode.rb:63:in `sudo_mode'
    Processing by UsErrorsController#error_500 as HTML
      Parameters: {"id"=>"subversionsupport"}
      Current user: imc (id=3)
      Rendering plugins/usability/app/views/errors/error_status.html.erb
      Rendered plugins/usability/app/views/errors/error_status.html.erb (14.4ms)
    Completed 500 Internal Server Error in 41ms (Views: 32.8ms | ActiveRecord: 3.7ms)

**Comment by poxtihc** [comment]
Same problem with easygantt

```
Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.5
  easy_baseline                  1.4
  easy_gantt                     1.12
  easy_gantt_pro                 1.10
  easy_gantt_resources           1.7
  extra_queries                  2.3.9
  global_roles                   2.2.5
  redmine_code_review            1.0.0
```

```
  Rendered projects/settings.html.erb within layouts/base (468.2ms)
Completed 500 Internal Server Error in 523ms (ActiveRecord: 16.6ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x00007fac28b79bf8>:0x0000558a2cbdda60>
Did you mean?  project_issues_path):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>

plugins/redmine_code_review/lib/code_review_projects_helper_patch.rb:22:in `project_settings_tabs'
plugins/easy_gantt_resources/lib/easy_gantt_resources/redmine_patch/helpers/projects_helper.rb:16:in `project_settings_tabs_with_easy_gantt_resources'
plugins/redmine_code_review/lib/code_review_projects_helper_patch.rb:22:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__856941258763745328_70188699481220'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by mckaygerhard** [comment]
git must be 2.11 as max, puff thos fashioned programs...

**Comment by HereInMyOwnSkin** [comment]
You can follow this fix: https://github.com/haru/redmine_code_review/issues/21#issue-643065424
