### ISSUE TITLE
Internal Error after installing redmine_code_review version 0.9.0 on localhost: 3000

### ISSUE THREAD

**Issue by Stasroot1** [haru/redmine_code_review#6]
Internal Error after installing redmine_code_review version 0.9.0 on localhost: 3000
After installing the module, the redmine does not start. Displays the message: Internal error

In the log, the following:

Started GET "/" for ::1 at 2017-12-21 03:23:23 +0300
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (36.8ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.5ms)
Completed 500 Internal Server Error in 296ms (ActiveRecord: 6.9ms)

ActionView::Template::Error (Missing partial code_review/_html_header with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "/home/sat/Redmine/redmine-3.4.3/app/views"
):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: 
    18: <%= yield :header_tags -%>
    19: </head>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__3324507243434119514_47166554901620'
  app/controllers/application_controller.rb:491:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:489:in `render_error'
  app/controllers/application_controller.rb:477:in `render_404'
  app/controllers/application_controller.rb:501:in `missing_template

**Comment by haru** [comment]
Does "/home/sat/Redmine/redmine-3.4.3/plugins/redmine_code_review/app/views/code_review/_html_header.html.erb" exist?

**Comment by Stasroot1** [comment]
Hello! I can not say from memory, as I can not look anymore. Removed the module.
   However, I will re-put it on Sunday or Monday, the result I will write off again and in detail what I did. Thank you.

**Comment by Stasroot1** [comment]
1. I downloaded the first time your module here: https://github.com/haru/redmine_code_review/archive/master.zip and installed it according to the instructions: https://github.com/haru/redmine_code_review/blob/master/README .rdoc
As a result, I received the specified error. Having carefully studied your question, I saw: you ask about the presence of /home/sat/Redmine/redmine-3.4.3/plugins/redmine_code_review/, but I do not have such a directory. I have /home/sat/Redmine/redmine-3.4.3/plugins/redmine_code_review-master/ In this directory, the requested file is.

Thinking about what could be the case began to look that to what. It turns out when downloading from the above link is downloaded archive in the title which is "-master" at the end.

And after repeating the installation in the same way again received an error. However, if you download the archive with the module from the page: https://github.com/haru/redmine_code_review/releases, more precisely: https://github.com/haru/redmine_code_review/releases/download/0.9.0/redmine_code_review-0.9.0 .zip and performing the installation in the same sequence as in the specified instruction, then everything works as expected.

Removed the correct installation and installed the new one with -master on the end, after repeating the initial error, renamed the folder redmine_code_review-master in redmine_code_review And it seems everything worked, except http: // localhost: 3000 / projects / projname

For this reason, I delete the module from -master and put the new downloaded distribution with https://github.com/haru/redmine_code_review/releases/download/0.9.0/redmine_code_review-0.9.0.zip

**Comment by Stasroot1** [comment]
2. Edit the file https://github.com/haru/redmine_code_review/blob/master/README.rdoc in order to avoid the autospackaging of the archive-master downloaded from the github, replacing in it:
Copy the plugin directory into the plugins directory
on
Copy the contents of the module folder to: plugins_directory / redmine_code_review
3. Add to the instructions section to remove the module by writing in it that you need to execute the command to delete: RAILS_ENV = production bundle exec rake redmine: plugins: migrate NAME = redmine_code_review VERSION = 0 by going to the directory with the redmine installed.
